apiVersion: apps/v1
kind: Deployment
metadata:
  name: waittimes-app
  namespace: waittimes
  labels:
    app: waittimes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waittimes-app
  template:
    metadata:
      labels:
        app: waittimes-app
    spec:
      containers:
      - name: waittimes-app
        image: public.ecr.aws/b7c8g1g5/linuxeclipsed/wait-times:25.06.10
        ports:
        - containerPort: 5173
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            secretKeyRef:
              name: waittimes
              key: REACT_APP_API_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waittimes-api
  namespace: waittimes
  labels:
    app: waittimes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waittimes-api
  template:
    metadata:
      labels:
        app: waittimes-api
    spec:
      containers:
      - name: waittimes-api
        image: public.ecr.aws/b7c8g1g5/linuxeclipsed/wait-times-api:25.06.10
        ports:
        - containerPort: 8000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: waittimes
              key: mysql-password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: waittimes
              key: mysql-user
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: waittimes
              key: DB_HOST
        - name: DB_NAME
          value: waiting_room